//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerSolutionsLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareerSolutionsEntities : DbContext
    {
        public CareerSolutionsEntities()
            : base("name=CareerSolutionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Job_Seeker> Job_Seeker { get; set; }
        public virtual DbSet<Job_Seeker_Professional> Job_Seeker_Professional { get; set; }
        public virtual DbSet<Jobs_Posted> Jobs_Posted { get; set; }
    }
}
