//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerSolutionsLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Jobs_Posted = new HashSet<Jobs_Posted>();
        }
    
        public int compId { get; set; }
        public string compName { get; set; }
        public string compBranch { get; set; }
        public string compAddress { get; set; }
        public string compCity { get; set; }
        public string compState { get; set; }
        public long oompPhone { get; set; }
        public string compEmail { get; set; }
        public string compPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs_Posted> Jobs_Posted { get; set; }
    }
}
