//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerSolutionsLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Seeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Seeker()
        {
            this.Job_Seeker_Professional = new HashSet<Job_Seeker_Professional>();
        }
    
        public int jsID { get; set; }
        public string jsFullName { get; set; }
        public string jsEmail { get; set; }
        public string jsPassword { get; set; }
        public long jsPhone { get; set; }
        public string jsGender { get; set; }
        public System.DateTime jsDOB { get; set; }
        public string jsCity { get; set; }
        public string jsState { get; set; }
        public string jsMaritalStatus { get; set; }
        public string jsLanguagePreferred { get; set; }
        public string jsResumeFileName { get; set; }
        public string jsHighestQuaification { get; set; }
        public string jsMajor { get; set; }
        public string jsUniversity { get; set; }
        public string jsInstitute { get; set; }
        public int jsYearOfGraduation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Seeker_Professional> Job_Seeker_Professional { get; set; }
    }
}
